spring.datasource.url=jdbc:postgresql://dpg-d8a0t0v7f7vs73cm4tm0-a.virginia-postgres.render.com:5432/beautyboutique

spring.datasource.username=saniya

spring.datasource.password=wxqx0dD8sDoDFi9phFiGBCs8HxvF7nFU

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true